### ISSUE TITLE
GH actions now disallows set-env by default

### ISSUE THREAD

**Issue by black-puppydog** [staltz/ssb-keys-neon#28]
Used here:
https://github.com/staltz/ssb-keys-neon/blob/e250744808685aeeb33c62ceb6ef52162ec09ff9/.github/workflows/main.yml#L206

I stumbled over this while playing with my own branch, and I see you also have a failed workflow for the same reason.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands

Not sure how much work this will be

**Comment by staltz** [comment]
Supposedly fixed now
